### ISSUE TITLE
Shafts can't be crafted

### ISSUE THREAD

**Issue by Revemohl** [JPANv2/UnuBattleRods#2]
They exist in-game as you can cheat them in, but they don't have a working recipe (and thus, they don't show up on Recipe Browser either). 
This is just a wild guess from someone who has no modding experience, but could it be because they use "base.AddRecipes();" instead of "recipe.AddRecipe();" to close the recipe?

**Comment by JPANv2** [comment]
Should be fixed in v 1.2
